name: Bug Report Form
description: Create a bug report
labels: bug
body:
    -   type: textarea
        attributes:
            label: Describe the bug
            description: A clear desribe about the bug
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Additional context
            description: Usually ask for crash log, so it would be best if you could attach the game log or crash report.
    -   type: markdown
        attributes:
            value: "You can paste your game log or crash report on [mclo.gs](https://mclo.gs/)"