name: Feature Request
description: Suggest ideas for Easycraft
labels: suggestion
body:
    -   type: textarea
        attributes:
            label: Your Suggestion?
            description: It should be in the title, but maybe you want to give more info for the title
    -   type: textarea
        attributes:
            label: Do I Really Need To Add Your Suggestion And Why?
            description: Tell me a detailed reason why i need to add your suggestion, your idea could affect many players, not just yourself
        validations:
            required: true